In [13]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [4]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code to print the data types of both the variables.

Yes, there is a difference in the data type of variables list_ and array_list. The variable list_ is a Python list containing string elements, while the variable array_list is a NumPy array with a data type inferred from the elements of the list.

In [5]:
print(type(list_[0]))
print(array_list.dtype)

<class 'str'>
<U1


Q2. Write a code to print the data type of each and every element of both the variables list_ and array_list.

In [6]:
# For list_
for element in list_:
    print(type(element))

# For array_list
for element in np.nditer(array_list):
    print(element.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<U1
<U1
<U1
<U1
<U1


Q3. Considering the following changes in the variable array_list: array_list = np.array(object = list_, dtype = int) Will there be any difference in the data type of the elements present in both the variables, list_ and array_list? If so then print the data types of each and every element present in both the variables, list_ and array_list.

In [7]:
array_list = np.array(object = list_, dtype = int)

Yes, there will be a difference in the data type of the elements present in both variables. When creating array_list with the dtype=int, the elements will be converted to integers.

In [8]:
# For list_
for element in list_:
    print(type(element))

# For array_list
for element in np.nditer(array_list):
    print(element.dtype)


<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
int64
int64
int64
int64
int64


In [9]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [10]:
# (i) shape
print(num_array.shape)

# (ii) size
print(num_array.size)


(2, 3)
6


Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [11]:
zeros_array = np.zeros((3, 3))
print(zeros_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Q6. Create an identity matrix of shape (5, 5) using numpy functions.

In [12]:
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
